### ISSUE TITLE
Does it work in graylog2 0.20?

### ISSUE THREAD

**Issue by seqizz** [ossobv/graylog2-plugin-alarmcallback-exec#4]
Would this work in latest rc?

**Comment by dfch** [comment]
I know this is rather late, but anyway (and not to be meant as a shameless plug)... I had a similar requirement but did not see that your plugin already existed so we wrote the somewhat very similar [SCRIPT AlarmCallback Plugin](https://github.com/dfch/biz.dfch.j.graylog2.plugin.alarm.execscript) that lets you execute arbitrary scripts (and nost just system commands). This plugin was written against the v0.92.3 plugin architecture, but for AlarmCallbacks in v1.0.0 not that much changed. Maybe this can help.

**Comment by wdoekes** [comment]
Nice. If I can deprecate this thing, all the better.

I don't immediately see how I can configure it to send a mail with the pertinent info though.
Could you expand your example scripts and/or the documentation?

I'll gladly update the README here to point to your version.

**Comment by dfch** [comment]
I updated the [example script](https://github.com/dfch/biz.dfch.j.graylog2.plugin.alarm.execscript/blob/master/src/main/resources/bizDfchMessageAlarmScript.js) and tested with some other script languages as well like [Python via Jython](http://stackoverflow.com/questions/2671768/calling-python-from-java-through-scripting-engine-jython) (if you specify an unsupported script engine an exception is written to the graylog log file).
So essentially you will get the `Message` object passed down into the script session where you can extract all the fields you like and work with that. Maybe with `Javascript` it does not totally fit your needs, but when combined with `Python` I think it is pretty powerful.

**Comment by wdoekes** [comment]
Thanks for the quick feedback. I'll get to updating this stale repo this week.
